--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 29/05/2022 16:40:07
-- Server version: 10.6.8
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database

CREATE DATABASE db_calculadora
CHARACTER SET utf8mb3
COLLATE utf8mb3_general_ci;

--
USE db_calculadora;

--
-- Drop table `historico`
--
DROP TABLE IF EXISTS historico;

--
-- Drop table `usuario`
--
DROP TABLE IF EXISTS usuario;

--
-- Set default database
--
USE db_calculadora;

--
-- Create table `usuario`
--
CREATE TABLE usuario (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Nome varchar(255) NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

--
-- Create table `historico`
--
CREATE TABLE historico (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Operacao varchar(255) NOT NULL,
  Resultado varchar(255) DEFAULT NULL,
  UsuarioId int(11) NOT NULL,
  Data datetime NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 22,
AVG_ROW_LENGTH = 780,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;

-- 
-- Dumping data for table usuario
--
INSERT INTO usuario VALUES
(1, 'Guilherme'),
(2, 'Alexandre'),
(3, 'Gustavo'),
(4, 'Gisele'),
(5, 'Gusatvo');

-- 
-- Dumping data for table historico
--
INSERT INTO historico VALUES
(1, '03+3+(32-3+66)', '101', 1, '2022-05-29 15:12:41'),
(2, '33+(65+36-22)', '112', 1, '2022-05-29 15:47:16'),
(3, '33+(65+36-22)', '112', 1, '2022-05-29 15:47:40'),
(4, '1+1', '2', 1, '2022-05-29 15:52:17'),
(5, '1+2', '3', 1, '2022-05-29 15:53:17'),
(6, '11+11', '22', 1, '2022-05-29 15:55:02'),
(7, '33-11', '22', 2, '2022-05-29 15:55:17'),
(8, '33-11', '22', 3, '2022-05-29 15:55:38'),
(9, '033+66', '93', 3, '2022-05-29 15:55:56'),
(10, '33+33', '66', 1, '2022-05-29 16:06:41'),
(11, '32+33', '65', 1, '2022-05-29 16:08:31'),
(12, '33+33', '66', 1, '2022-05-29 16:10:57'),
(13, '33+33', '66', 1, '2022-05-29 16:12:43'),
(14, '032-32', '-6', 1, '2022-05-29 16:13:09'),
(15, '032-32', '-6', 1, '2022-05-29 16:13:31'),
(16, '33+6', '39', 1, '2022-05-29 16:16:03'),
(17, '33+62+2', '97', 1, '2022-05-29 16:16:19'),
(18, '33-6', '27', 1, '2022-05-29 16:17:34'),
(19, '33-57', '-24', 1, '2022-05-29 16:29:30'),
(20, '1+1', '2', 2, '2022-05-29 16:30:22'),
(21, '3+3', '6', 1, '2022-05-29 16:31:10');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;